### ISSUE TITLE
Can not start node.js process (node), make sure your system has node.js installed.

### ISSUE THREAD

**Issue by briankitt** [wallabyjs/calculator-sample#1]
I think there is a bug in Wallaby.  I was working in another project, and purchases wallaby, and started getting the above message.  I tried everything I could find on the internet, nothing fixed it.  I know for a fact I have node installed correctly, I've been using it for years.  I can open a command line up and node executes just find.  It's in my path, and it's correct.
I added it to node\runner.
I added it to my environment variables.
So I downloaded the calculator-sample, hoping to resolve this error, and I get the same error with this demo.
There MUST be a bug in Wallaby.  Please fix this.  It's highly annoying that I purchase this product, and I can't even start it.
I am on Windows 10.  I have Node JS 64 bit.

**Comment by ArtemGovorov** [comment]
What IDE/editor are you using?

**Comment by briankitt** [comment]
VS Code.

**Comment by briankitt** [comment]
Additional information:

I have 2 computers.  I think I keep them exactly in sync.  The second one,
everything works fine.  As far as I know they are set up identical, I try
to keep them mirror images of each other.

**Comment by ArtemGovorov** [comment]
Try setting the path to your node exe via the `wallaby.node` setting in VS Code as described at https://wallabyjs.com/docs/intro/install.html#nodejs-1.

**Comment by briankitt** [comment]
I didn't have a settings.json, I added one, with wallaby.node as the only
entry.  that appears to have fixed it.
I only have 1 install of Node, why did it not work to have it in my path?

**Comment by ArtemGovorov** [comment]
@briankitt It's hard to tell, but given that the other machine works fine, there may be an issue with node.exe possibly being incorrectly set in your PATH, or something like that. All we do by default is using `node`. Try comparing your settings on the 2 machines you have, there must be some difference.
